### ISSUE TITLE
Implementing private dataset

### ISSUE THREAD

**Issue by hankw2003** [Takaaki-Saeki/ssl_speech_restoration#10]
Hello. Thanks for publishing your code!
When implementing my own dataset on this training method, a few problem occurs, especially the "dataset" module, and the problem seems mainly focusing on "wavstask".
![image](https://github.com/Takaaki-Saeki/ssl_speech_restoration/assets/117650786/3ae27892-0749-4c10-851a-d01d14b129dd)
![image](https://github.com/Takaaki-Saeki/ssl_speech_restoration/assets/117650786/27e12cd5-3e3a-4ee4-9c4c-af2f6e176eb9)

Just want to know if similar problems have occurred to you when conducting dual learning, thanks!
If any further information is needed, please let me know.

**Comment by Takaaki-Saeki** [comment]
Hi, thanks for letting me know it.

Fixed this issue in this PR.
https://github.com/Takaaki-Saeki/ssl_speech_restoration/pull/11

Also, please refer to this updated version if you need.
https://github.com/Takaaki-Saeki/ssl_speech_restoration_v2
