### ISSUE TITLE
No versions in requirements.txt

### ISSUE THREAD

**Issue by chrisbaume** [Takaaki-Saeki/ssl_speech_restoration#6]
Hello. Thanks for publishing your code and checkpoints 😃 

I've come across the following error
```
dataset.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
```

Although this warning disappears when you add `dtype=object`, I came across another problem later on and was unable to get the system running.

My suggestion is to add version numbers for each dependency in `requirements.txt`. That way, we can know which versions of each library form a working solution, and the code will continue to work in the future after libraries have changed.

**Comment by Takaaki-Saeki** [comment]
Sorry for the delay and thank you so much for the suggestion.
I have added the version numbers.
If you have any further problems, please let me know.
