### ISSUE TITLE
Pretrained models not available? 

### ISSUE THREAD

**Issue by simranjumani** [Takaaki-Saeki/ssl_speech_restoration#7]
The [link](https://github.com/Takaaki-Saeki/ssl_speech_restoration/blob/master/pretrained_models.md) for the pretrained models says the file is in the owner's trash. Is there any other place it has been made available? 
![image](https://github.com/Takaaki-Saeki/ssl_speech_restoration/assets/44533773/48520fed-14b0-443d-9484-17256c3dcf95)

**Comment by Takaaki-Saeki** [comment]
Hi, sorry for the inconvenience. It is due to the storage limit of google drive. I have restored the files.
If it does not show up again, please let me know.
